# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - pip install -r requirements_dev.txt
  - python setup.py develop

script: pytest tests
